(function(){
  'use strict';
  const FOREX_MODE_ID='flowsignalForexMode', BINARY_MODE_ID='flowsignalBinaryMode';
  const MODE_KEY='flowsignal_trading_mode', CONNECTION_KEY='flowsignal_deriv_connection_id', STATE_KEY='flowsignal_deriv_oauth_state', VERIFIER_KEY='flowsignal_deriv_pkce_verifier', USER_KEY='flowsignal_binary_user_id', ACCOUNT_KEY='flowsignal_deriv_account_id';
  const FOREX_ALERT_PREF_KEY='soundEnabled', FOREX_ALERT_GUARD_KEY='flowsignal_binary_oauth_forex_alert_guard';
  const BACKEND=(location.hostname==='localhost'||location.hostname==='127.0.0.1')?'http://127.0.0.1:8001':`${location.origin}/api/proxy`;
  const CUSTOMER_API=`${BACKEND}/user`;
  const POLL_MS=6000, DEFAULT_STAKE=10, EXPIRY_MINUTES=5;
  const STRATEGY_VERSION='DERIV_BINARY_SIMPLE_5M_1';
  const RULE_HASH='755ea79159b49281b0671846d0883ec34702efa55c2cf397aafac47058f8e3cb';
  let mounted=false, pollTimer=null, executionBusy=false, lastLocalSignalId='', selectedAccount=null;

  function getCurrentFlowSignalUserId(){let value=localStorage.getItem(USER_KEY); if(!value){value=crypto.randomUUID(); localStorage.setItem(USER_KEY,value);} return value;}
  function isLegacyAdmin(){return sessionStorage.getItem('flowsignal_tab_role')==='admin'&&!sessionStorage.getItem('flowsignal_user_session_token');}
  function derivApi(path){return `${BACKEND}${isLegacyAdmin()?'/deriv':'/user/deriv'}${path}`;}
  function adminBody(payload={}){return isLegacyAdmin()?{...payload,user_id:getCurrentFlowSignalUserId()}:payload;}
  function normalizeMode(value){return String(value||'').toLowerCase()==='binary'?'binary':'forex';}
  function currentMode(){return normalizeMode(localStorage.getItem(MODE_KEY));}
  function binaryVisible(){return currentMode()==='binary';}
  function accountId(account){return account?.account_id||account?.id||account?.loginid||'';}
  function accountType(account){return String(account?.account_type_normalized||account?.account_type||'UNKNOWN').toUpperCase();}
  function setText(id,value){const el=document.getElementById(id); if(el) el.textContent=value;}
  function toggleClass(id,name,on){document.getElementById(id)?.classList.toggle(name,Boolean(on));}
  function formatMoney(value,currency='USD'){const amount=Number(value); if(!Number.isFinite(amount)) return `-- ${currency}`; try{return `${new Intl.NumberFormat(undefined,{style:'currency',currency,minimumFractionDigits:2}).format(amount)} ${currency}`;}catch(_error){return `$${amount.toFixed(2)} ${currency}`;}}
  function formatTime(value){if(value===null||value===undefined||value==='') return '--'; const number=Number(value); const date=Number.isFinite(number)?new Date(number<1e12?number*1000:number):new Date(value); return Number.isNaN(date.getTime())?'--':date.toLocaleString();}
  function escapeHtml(value){return String(value??'--').replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));}
  function normalizedResult(record){const outcome=String(record?.outcome||'').toUpperCase(); if(['WIN','WON'].includes(outcome)) return 'WIN'; if(['LOSS','LOST'].includes(outcome)) return 'LOSS'; if(outcome==='TIE') return 'TIE'; const status=String(record?.broker_status||'UNKNOWN').toUpperCase(); return ['RESERVED','PROPOSED','PURCHASED','OPEN','RUNNING'].includes(status)?'PENDING':status;}

  function beginForexAlertIsolationGuard(){const previous=localStorage.getItem(FOREX_ALERT_PREF_KEY); sessionStorage.setItem(FOREX_ALERT_GUARD_KEY,JSON.stringify({previous,startedAt:Date.now()})); localStorage.setItem(FOREX_ALERT_PREF_KEY,'false');}
  function restoreForexAlertIsolationGuard(){const raw=sessionStorage.getItem(FOREX_ALERT_GUARD_KEY); if(!raw) return; let state=null; try{state=JSON.parse(raw);}catch(_error){} window.setTimeout(()=>{const prior=state?.previous; if(prior===null||prior===undefined) localStorage.removeItem(FOREX_ALERT_PREF_KEY); else localStorage.setItem(FOREX_ALERT_PREF_KEY,String(prior)); sessionStorage.removeItem(FOREX_ALERT_GUARD_KEY); console.info('BINARY_OAUTH_FOREX_ALERT_GUARD_RESTORED');},15000);}
  if(sessionStorage.getItem(FOREX_ALERT_GUARD_KEY)){localStorage.setItem(FOREX_ALERT_PREF_KEY,'false'); restoreForexAlertIsolationGuard();}
  else if(!localStorage.getItem(MODE_KEY)) localStorage.setItem(MODE_KEY,'forex');
  function injectCss(){if(document.querySelector('link[data-flowsignal-binary-css]')) return; const link=document.createElement('link'); link.rel='stylesheet'; link.href='binary/binary.css?v=6'; link.dataset.flowsignalBinaryCss='true'; document.head.appendChild(link);}

  function binaryHtml(){return `<aside class="binary-sidebar" aria-label="Binary navigation"><div class="binary-brand"><span>⌁</span> FlowSignal</div><nav><button type="button" class="active" data-binary-section="dashboard">ϟ Binary Dashboard</button><button type="button" data-binary-section="accounts">♙ Deriv Accounts</button><button type="button" data-binary-section="history">▣ Binary History</button><button type="button" data-binary-section="settings">⚙ Settings</button><div class="binary-nav-separator"></div><button type="button" data-binary-section="documentation">▤ Documentation</button></nav><button type="button" id="binaryLogoutBtn" class="binary-logout">⇥ Log Out</button></aside>
  <main class="binary-dashboard"><header class="binary-page-header"><div><span class="binary-eyebrow">BINARY MODE</span><h1>Binary Dashboard</h1><p>Simple five-minute candle-direction execution.</p></div><div class="binary-header-actions"><span id="binaryHeaderConnection" class="binary-connection disconnected">DISCONNECTED</span><button id="binaryDerivConnectBtn" type="button">Connect Deriv</button><button id="binaryDerivDisconnectBtn" type="button" class="hidden">Disconnect</button></div></header>
  <section class="binary-layout"><div class="binary-center-column">
  <article class="binary-card binary-signal-card"><div class="binary-market-block"><span class="binary-eyebrow">BINARY MODE</span><div><strong>EURUSD</strong><b>5 MINUTE</b></div><p>Simple 5m Candle Signal</p></div><div class="binary-signal-state"><span class="binary-clock-icon">◷</span><div><div id="binaryDerivSignal" class="binary-signal wait">WAIT</div><p id="binarySignalCopy">Waiting for next signal</p><small>Standby for RISE or FALL</small></div></div><div class="binary-time-grid"><span>Last Signal<strong id="binaryLastSignalAt">--</strong></span><span>Last Update<strong id="binaryLastUpdateAt">--</strong></span></div></article>
  <article class="binary-card binary-contract-card"><div class="binary-card-heading"><div><span class="binary-eyebrow">ACTIVE CONTRACT</span><h2 id="binaryContractTitle">No Active Contract</h2></div><span id="binaryContractStatus" class="binary-status-pill neutral">IDLE</span></div><p id="binaryContractEmpty">When a signal is executed, contract details will appear here.</p><div id="binaryContractDetails" class="binary-contract-details hidden"><div><span>Direction</span><strong id="binaryContractDirection">--</strong></div><div><span>Account</span><strong id="binaryContractAccount">--</strong></div><div><span>Stake</span><strong id="binaryContractStake">--</strong></div><div><span>Contract ID</span><strong id="binaryContractId">--</strong></div><div><span>Broker entry</span><strong id="binaryContractEntry">--</strong></div><div><span>Potential payout</span><strong id="binaryContractPayout">--</strong></div><div><span>Purchase time</span><strong id="binaryContractPurchaseAt">--</strong></div><div><span>Expiry / settlement</span><strong id="binaryContractExpiry">--</strong></div><div><span>Countdown</span><strong id="binaryContractCountdown">--</strong></div></div></article>
  <article class="binary-card binary-history-card"><div class="binary-card-heading"><div><span class="binary-eyebrow">RECENT BINARY CONTRACTS</span><h2>Binary History</h2></div><button id="binaryHistoryRefresh" class="binary-history-refresh" type="button">Refresh</button></div><div class="binary-table-wrap"><table><thead><tr><th>Time</th><th>Direction</th><th>Account</th><th>Stake</th><th>Result</th><th>P/L</th><th>Status</th><th>Contract ID</th></tr></thead><tbody id="binaryHistoryRows"><tr><td colspan="8" class="binary-empty-row">No contracts yet</td></tr></tbody></table></div><p id="binaryHistorySummary" class="binary-history-summary">Select a connected Deriv account to load history.</p></article></div>
  <aside class="binary-right-column">
  <article class="binary-card" id="binaryAccountCard"><div class="binary-card-heading"><div><span class="binary-eyebrow">DERIV ACCOUNT</span><h2>Execution Account</h2></div><span id="binaryAccountBadge" class="binary-account-badge unknown">UNKNOWN</span></div><select id="binaryDerivAccountSelect" aria-label="Deriv account"><option value="">No connected account</option></select><strong id="binaryAccountId" class="binary-account-id">Not connected</strong><span id="binaryAccountBalance" class="binary-account-balance">--</span><span id="binaryAccountConnection" class="binary-muted">DISCONNECTED</span></article>
  <article class="binary-card binary-setting-card binary-auto-card"><div><span class="binary-eyebrow">BINARY AUTO</span><p>Status <strong id="binaryAutoStatusText">OFF</strong></p><small>This controls auto execution<br>for the selected Deriv account.</small></div><label class="binary-switch"><input id="binaryAutoToggle" type="checkbox" disabled><span></span><b id="binaryAutoLabel">OFF</b></label></article>
  <article class="binary-card binary-setting-card binary-stake-card"><div><span class="binary-eyebrow">STAKE</span><div class="binary-stake-display">$<strong id="binaryStakeDisplay">10.00</strong> <small id="binaryStakeCurrency">USD</small></div><p>Contract stake amount</p></div><div class="binary-stake-editor"><span>$</span><input id="binaryStake" type="number" min="0.01" step="0.01" value="10" disabled><button id="binarySaveSettings" type="button" disabled>Change Stake</button></div></article>
  <article class="binary-card binary-duration-card"><span class="binary-eyebrow">CONTRACT DURATION</span><strong>◷ &nbsp; 5 Minutes</strong><p>Fixed duration per trade</p><p>No SL / TP</p></article>
  <article class="binary-card binary-execution-card"><span class="binary-eyebrow">EXECUTION STATUS</span><ol class="binary-lifecycle"><li><span>◷ &nbsp; Signal</span><strong id="binaryStageSignal">WAIT</strong></li><li><span>◉ &nbsp; Eligibility</span><strong id="binaryStageEligibility">--</strong></li><li><span>◷ &nbsp; Proposal</span><strong id="binaryStageProposal">--</strong></li><li><span>⊕ &nbsp; Execution</span><strong id="binaryStageExecution">--</strong></li><li><span>◴ &nbsp; Settlement</span><strong id="binaryStageSettlement">--</strong></li></ol></article>
  <article class="binary-card binary-mapping-card"><span class="binary-eyebrow">SIGNAL MAPPING</span><div class="binary-mapping"><strong>↑ RISE <span>↓</span> CALL</strong><strong>↑ FALL <span>↓</span> PUT</strong></div><p class="binary-muted">5 minute duration · EURUSD<br>Previous completed candle direction</p></article>
  <article class="binary-card binary-system-card"><span class="binary-eyebrow">SYSTEM STATUS</span><p class="binary-all-systems"><i></i> All Systems Operational</p><div class="binary-system"><span>Binary Signal <strong id="binarySystemResearch">UNKNOWN</strong></span><span>Relay <strong id="binarySystemRelay">UNKNOWN</strong></span><span>Deriv Connection <strong id="binarySystemDeriv">DISCONNECTED</strong></span><span>Execution Engine <strong id="binarySystemExecution">IDLE</strong></span></div><p id="binaryDerivStatus" class="binary-inline-status">Waiting for connection</p></article></aside></section></main>`;}

  function bindBinaryEvents(root){root.querySelector('#binaryDerivConnectBtn')?.addEventListener('click',onConnectClick); root.querySelector('#binaryDerivDisconnectBtn')?.addEventListener('click',onDisconnectClick); root.querySelector('#binaryDerivAccountSelect')?.addEventListener('change',onAccountSelect); root.querySelector('#binarySaveSettings')?.addEventListener('click',saveBinarySettings); root.querySelector('#binaryHistoryRefresh')?.addEventListener('click',refreshHistory); root.querySelector('#binaryAutoToggle')?.addEventListener('change',async()=>{const enabled=document.getElementById('binaryAutoToggle').checked; setText('binaryAutoLabel',enabled?'ON':'OFF'); setText('binaryAutoStatusText',enabled?'ON':'OFF'); await saveBinarySettings();}); root.querySelector('#binaryLogoutBtn')?.addEventListener('click',()=>document.getElementById('logoutBtn')?.click()); root.querySelectorAll('[data-binary-section]').forEach(button=>button.addEventListener('click',()=>{root.querySelectorAll('[data-binary-section]').forEach(item=>item.classList.toggle('active',item===button)); if(button.dataset.binarySection==='accounts') document.getElementById('binaryAccountCard')?.scrollIntoView({behavior:'smooth',block:'start'}); if(button.dataset.binarySection==='history'){refreshHistory(); root.querySelector('.binary-history-card')?.scrollIntoView({behavior:'smooth',block:'start'});} if(button.dataset.binarySection==='settings') location.href='/profile.html';}));}
  function buildModeShell(){
    const desktopApp=document.getElementById('mainApp');
    const mobileApp=document.getElementById('mobileApp');
    const host=desktopApp||document.body;
    if(!desktopApp&&!mobileApp) return false;
    let forex=document.getElementById(FOREX_MODE_ID);
    if(!forex){
      forex=document.createElement('div'); forex.id=FOREX_MODE_ID; forex.className='flowsignal-mode-panel';
      if(desktopApp){Array.from(desktopApp.children).forEach(child=>forex.appendChild(child)); desktopApp.appendChild(forex);}
      else{mobileApp.insertAdjacentElement('beforebegin',forex); forex.appendChild(mobileApp);}
    }
    let selector=document.getElementById('flowsignalTradingModeSelector');
    if(!selector){selector=document.createElement('div'); selector.id='flowsignalTradingModeSelector'; selector.className='flowsignal-mode-selector'; selector.setAttribute('aria-label','Trading mode'); selector.innerHTML='<button type="button" data-trading-mode="forex">FOREX</button><button type="button" data-trading-mode="binary">BINARY</button>'; host.insertBefore(selector,forex); selector.addEventListener('click',event=>{const button=event.target.closest('[data-trading-mode]'); if(button) setMode(button.dataset.tradingMode);});}
    let binary=document.getElementById(BINARY_MODE_ID);
    if(!binary){binary=document.createElement('section'); binary.id=BINARY_MODE_ID; binary.className='flowsignal-mode-panel flowsignal-binary-mode'; binary.innerHTML=binaryHtml(); host.appendChild(binary); bindBinaryEvents(binary);}
    applyMode(currentMode()); return true;
  }
  function applyMode(mode){const normalized=normalizeMode(mode), forex=document.getElementById(FOREX_MODE_ID), binary=document.getElementById(BINARY_MODE_ID); if(forex){forex.hidden=normalized!=='forex'; forex.setAttribute('aria-hidden',normalized==='forex'?'false':'true');} if(binary){binary.hidden=normalized!=='binary'; binary.setAttribute('aria-hidden',normalized==='binary'?'false':'true');} document.querySelectorAll('#flowsignalTradingModeSelector [data-trading-mode]').forEach(button=>{const active=button.dataset.tradingMode===normalized; button.classList.toggle('active',active); button.setAttribute('aria-pressed',String(active));}); document.body?.setAttribute('data-trading-mode',normalized); if(normalized==='binary'){refreshAll(); startPolling();}else stopPolling(); document.dispatchEvent(new CustomEvent('flowsignal:trading-mode-changed',{detail:{mode:normalized}}));}
  function setMode(mode){const normalized=normalizeMode(mode); localStorage.setItem(MODE_KEY,normalized); applyMode(normalized); return normalized;}
  function setStatus(text,isError=false){setText('binaryDerivStatus',text); toggleClass('binaryDerivStatus','error',isError);}
  function genuineV5Signal(data){const direction=String(data?.signal||data?.direction||'').toUpperCase(); if(!['RISE','FALL'].includes(direction)||data?.strategy_version!==STRATEGY_VERSION||data?.rule_hash!==RULE_HASH) return false; const match=String(data?.signal_id||'').match(/^DERIV_BINARY_SIMPLE_5M_1:frxEURUSD:(\d{10,13}):(RISE|FALL)$/); if(!match||match[2]!==direction) return false; const timestamp=Number(match[1]); return Number.isFinite(timestamp)&&timestamp>0;}
  function renderSignal(data){const requested=String(data?.signal||'WAIT').toUpperCase(); const direction=requested==='WAIT'?'WAIT':genuineV5Signal(data)?requested:'WAIT'; const el=document.getElementById('binaryDerivSignal'); if(el){el.textContent=direction; el.className=`binary-signal ${direction.toLowerCase()}`;} setText('binarySignalCopy',direction==='RISE'?'5-minute RISE signal':direction==='FALL'?'5-minute FALL signal':'Waiting for next signal'); setText('binaryStageSignal',direction); setText('binaryLastUpdateAt',new Date().toLocaleString()); if(direction!=='WAIT') setText('binaryLastSignalAt',formatTime(data.decision_timestamp||data.timestamp||String(data.signal_id).split(':')[2])); return direction;}

  function randomVerifier(){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~'; const bytes=crypto.getRandomValues(new Uint8Array(64)); return Array.from(bytes,b=>alphabet[b%alphabet.length]).join('');}
  async function codeChallenge(verifier){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)); return btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
  function randomState(){return Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');}
  async function getConfig(){const response=await fetch(derivApi('/config'),{cache:'no-store'}); if(!response.ok) throw new Error(`backend ${response.status}`); return response.json();}
  function safeDerivMessage(code,fallback='Could not connect Deriv.'){const messages={AUTHENTICATION_REQUIRED:'Your FlowSignal session expired. Log in again.',DERIV_OAUTH_STATE_EXPIRED:'The Deriv login window expired. Start the connection again.',DERIV_OAUTH_STATE_REPLAYED:'This Deriv callback was already used. Start a new connection.',DERIV_OAUTH_USER_MISMATCH:'This Deriv login belongs to another FlowSignal account.',DERIV_NOT_CONNECTED:'Deriv is disconnected. Connect again.',DERIV_TOKEN_INVALID:'Your Deriv authorization expired or was revoked. Connect again.'}; return messages[String(code||'')]||fallback;}
  async function onConnectClick(event){event.preventDefault(); event.stopPropagation(); const button=event.currentTarget; button.disabled=true; button.textContent='Connecting…'; setStatus('Preparing secure Deriv login…'); try{const cfg=await getConfig(); if(!cfg?.configured||!cfg?.client_id||!cfg?.authorization_url) throw new Error('DERIV_CONFIG_UNAVAILABLE'); const verifier=randomVerifier(), state=randomState(), challenge=await codeChallenge(verifier); if(!isLegacyAdmin()){const stateResponse=await fetch(derivApi('/oauth/state'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,code_verifier:verifier})}); const statePayload=await stateResponse.json().catch(()=>({})); if(!stateResponse.ok) throw new Error(statePayload.detail||'DERIV_OAUTH_START_FAILED');} sessionStorage.setItem(VERIFIER_KEY,verifier); sessionStorage.setItem(STATE_KEY,state); localStorage.setItem(MODE_KEY,'binary'); const url=new URL(cfg.authorization_url); url.searchParams.set('response_type','code'); url.searchParams.set('client_id',cfg.client_id); url.searchParams.set('redirect_uri',cfg.redirect_uri); url.searchParams.set('scope',cfg.scope||'trade'); url.searchParams.set('state',state); url.searchParams.set('code_challenge',challenge); url.searchParams.set('code_challenge_method','S256'); beginForexAlertIsolationGuard(); window.location.href=url.toString();}catch(error){console.error('BINARY_DERIV_CONNECT_ERROR',error); setStatus(safeDerivMessage(error.message,'Unable to start Deriv login. Please try again.'),true); button.disabled=false; button.textContent='Connect Deriv';}}
  async function onDisconnectClick(event){event.preventDefault(); const id=localStorage.getItem(CONNECTION_KEY); try{if(id){const response=await fetch(derivApi('/disconnect'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connection_id:id})}); if(!response.ok) return setStatus('Unable to disconnect Deriv. Please try again.',true);}}catch(error){console.warn('BINARY_DERIV_DISCONNECT_WARNING',error); return setStatus('Unable to disconnect Deriv. Please try again.',true);} localStorage.removeItem(CONNECTION_KEY); localStorage.removeItem(ACCOUNT_KEY); selectedAccount=null; lastLocalSignalId=''; await refreshStatus(); setStatus('Deriv disconnected safely.');}
  function renderAccount(account,connected){const type=connected?accountType(account):'UNKNOWN', id=connected?accountId(account):'', currency=account?.currency||'USD'; setText('binaryAccountBadge',type); const badge=document.getElementById('binaryAccountBadge'); if(badge) badge.className=`binary-account-badge ${type.toLowerCase()}`; setText('binaryAccountId',id||'Not connected'); setText('binaryAccountBalance',connected?formatMoney(account?.balance,currency):'--'); setText('binaryAccountConnection',connected?'CONNECTED':'DISCONNECTED'); setText('binaryHeaderConnection',connected?'CONNECTED':'DISCONNECTED'); setText('binarySystemDeriv',connected?'CONNECTED':'DISCONNECTED'); setText('binaryStakeCurrency',`${currency} per contract`); ['binaryHeaderConnection','binaryAccountConnection'].forEach(name=>{const el=document.getElementById(name); el?.classList.toggle('connected',connected); el?.classList.toggle('disconnected',!connected);});}
  async function loadBinarySettings(){if(!selectedAccount) return; const suffix=isLegacyAdmin()?`/${encodeURIComponent(getCurrentFlowSignalUserId())}`:''; const response=await fetch(`${derivApi('/binary/account-settings')}${suffix}/${encodeURIComponent(accountId(selectedAccount))}`,{cache:'no-store'}); if(!response.ok) return; const data=await response.json(); const toggle=document.getElementById('binaryAutoToggle'), stake=document.getElementById('binaryStake'), save=document.getElementById('binarySaveSettings'); if(toggle){toggle.checked=Boolean(data.binary_auto_enabled); toggle.disabled=false;} if(stake){stake.value=String(data.binary_stake??DEFAULT_STAKE); stake.disabled=false;} if(save) save.disabled=false; const autoText=data.binary_auto_enabled?'ON':'OFF'; setText('binaryAutoLabel',autoText); setText('binaryAutoStatusText',autoText); setText('binaryStakeDisplay',Number(data.binary_stake??DEFAULT_STAKE).toFixed(2));}
  async function saveBinarySettings(){if(!selectedAccount) return setStatus('Select a Deriv account',true); const stake=Number(document.getElementById('binaryStake').value); if(!Number.isFinite(stake)||stake<=0) return setStatus('Enter a valid stake',true); const response=await fetch(derivApi('/binary/account-settings'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(adminBody({deriv_account_id:accountId(selectedAccount),enabled:document.getElementById('binaryAutoToggle').checked,stake}))}); const data=await response.json().catch(()=>({})); if(!response.ok) return setStatus(safeDerivMessage(data.detail,'Binary settings could not be saved. Please try again.'),true); await loadBinarySettings(); setStatus(`${data.account_type} ${data.deriv_account_id} · Binary Auto ${data.binary_auto_enabled?'ON':'OFF'}`);}
  async function onAccountSelect(event){const connectionId=localStorage.getItem(CONNECTION_KEY), id=event.target.value; if(!connectionId||!id) return; const response=await fetch(derivApi('/account/select'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(adminBody({connection_id:connectionId,deriv_account_id:id}))}); const data=await response.json().catch(()=>({})); if(!response.ok) return setStatus(safeDerivMessage(data.detail,'That Deriv account could not be selected.'),true); localStorage.setItem(ACCOUNT_KEY,id); await refreshStatus();}
  async function refreshStatus(){const root=document.getElementById(BINARY_MODE_ID); if(!root) return false; const connect=root.querySelector('#binaryDerivConnectBtn'), disconnect=root.querySelector('#binaryDerivDisconnectBtn'), connectionId=localStorage.getItem(CONNECTION_KEY); if(!connectionId){selectedAccount=null; renderAccount(null,false); setStatus('Waiting for connection'); connect?.classList.remove('hidden'); disconnect?.classList.add('hidden'); return false;} try{const response=await fetch(derivApi('/status'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connection_id:connectionId}),cache:'no-store'}); const data=await response.json().catch(()=>({})); if(!response.ok||!data.connected){localStorage.removeItem(CONNECTION_KEY); selectedAccount=null; renderAccount(null,false); setStatus('Deriv connection expired',true); connect?.classList.remove('hidden'); disconnect?.classList.add('hidden'); return false;} connect?.classList.add('hidden'); disconnect?.classList.remove('hidden'); const select=document.getElementById('binaryDerivAccountSelect'), wanted=data.selected_account_id||localStorage.getItem(ACCOUNT_KEY)||''; select.innerHTML=(data.accounts||[]).map(account=>{const id=accountId(account); return `<option value="${id}" ${id===wanted?'selected':''}>${accountType(account)} · ${id}</option>`;}).join('')||'<option value="">No connected account</option>'; selectedAccount=(data.accounts||[]).find(account=>accountId(account)===wanted)||null; if(!selectedAccount){renderAccount(null,true); setStatus('Deriv connected · select an account',true); return false;} localStorage.setItem(ACCOUNT_KEY,accountId(selectedAccount)); renderAccount(selectedAccount,true); await loadBinarySettings(); await refreshExecution(); setStatus(`Deriv ${accountType(selectedAccount)} connected`); return true;}catch(error){console.warn('BINARY_DERIV_STATUS_WARNING',error); setStatus('Deriv status unavailable',true); return false;}}

  function executionValue(data,...keys){for(const key of keys){if(data?.[key]!==undefined&&data?.[key]!==null) return data[key];} return null;}
  function renderExecution(snapshot){const running=snapshot?.running_contract||null, latest=snapshot?.last_execution||null, record=running||latest; if(!record){setText('binaryContractTitle','No Active Contract'); setText('binaryContractStatus','IDLE'); toggleClass('binaryContractDetails','hidden',true); toggleClass('binaryContractEmpty','hidden',false); setText('binarySystemExecution','IDLE'); return;} const status=String(executionValue(record,'broker_status','status','outcome')||(running?'RUNNING':'UNKNOWN')).toUpperCase(), direction=String(executionValue(record,'direction')||'--').toUpperCase(), contractType=executionValue(record,'contract_type'), currency=executionValue(record,'currency')||selectedAccount?.currency||'USD', stake=executionValue(record,'stake','purchase_price','buy_price'), payout=executionValue(record,'settlement_payout','payout','potential_payout'), settled=['WIN','LOSS','WON','LOST','SOLD','SETTLED'].includes(status)||Boolean(record?.settlement_timestamp); setText('binaryContractTitle',settled?normalizedResult(record):`${direction} RUNNING`); setText('binaryContractStatus',settled?normalizedResult(record):'RUNNING'); toggleClass('binaryContractDetails','hidden',false); toggleClass('binaryContractEmpty','hidden',true); setText('binaryContractDirection',`${direction}${contractType?` · ${contractType}`:''}`); setText('binaryContractAccount',`${accountType(selectedAccount)} · ${accountId(selectedAccount)}`); setText('binaryContractStake',formatMoney(stake,currency)); setText('binaryContractId',executionValue(record,'contract_id')||'--'); setText('binaryContractEntry',executionValue(record,'entry_spot','entry_price','buy_price','purchase_price')??'--'); setText('binaryContractPayout',formatMoney(payout,currency)); setText('binaryContractPurchaseAt',formatTime(executionValue(record,'purchase_time','purchase_timestamp','created_at'))); setText('binaryContractExpiry',formatTime(executionValue(record,'expiry_time','expiry_timestamp','settlement_timestamp','settled_at'))); setText('binaryContractCountdown',running?'RUNNING':'COMPLETE'); setText('binaryStageEligibility','ELIGIBLE'); setText('binaryStageProposal',executionValue(record,'proposal_id')?'ACCEPTED':'--'); setText('binaryStageExecution',executionValue(record,'contract_id')?'PURCHASED':'--'); setText('binaryStageSettlement',settled?normalizedResult(record):'PENDING'); setText('binarySystemExecution',running?'RUNNING':settled?'IDLE':'BLOCKED');}
  function renderHistory(payload){const rows=document.getElementById('binaryHistoryRows'); if(!rows) return; const items=Array.isArray(payload?.items)?payload.items:[]; if(!items.length){rows.innerHTML='<tr><td colspan="8" class="binary-empty-row">No contracts yet</td></tr>'; setText('binaryHistorySummary','No Binary contracts for this account.'); return;} rows.innerHTML=items.map(record=>{const currency=record.currency||'USD', result=normalizedResult(record), direction=`${record.direction||'--'}${record.contract_type?` · ${record.contract_type}`:''}`, account=`${record.account_type||'UNKNOWN'} · ${record.deriv_account_id||'--'}`, time=record.settlement_timestamp||record.purchase_timestamp||record.created_at; return `<tr title="Signal ${escapeHtml(record.signal_id)} · Strategy ${escapeHtml(record.strategy_version)}"><td data-label="Time">${escapeHtml(formatTime(time))}</td><td data-label="Direction">${escapeHtml(direction)}</td><td data-label="Account">${escapeHtml(account)}</td><td data-label="Stake">${escapeHtml(formatMoney(record.stake,currency))}</td><td data-label="Result"><span class="binary-result ${escapeHtml(result.toLowerCase())}">${escapeHtml(result)}</span></td><td data-label="P/L">${escapeHtml(formatMoney(record.profit_loss,currency))}</td><td data-label="Status">${escapeHtml(record.broker_status||'UNKNOWN')}</td><td data-label="Contract ID">${escapeHtml(record.contract_id||'--')}</td></tr>`;}).join(''); setText('binaryHistorySummary',`Showing ${items.length} of ${Number(payload.total??items.length)} recent contracts for ${accountId(selectedAccount)}.`);}
  async function refreshHistory(){if(!selectedAccount){renderHistory({items:[],total:0}); return;} try{const ownerPrefix=isLegacyAdmin()?`/${encodeURIComponent(getCurrentFlowSignalUserId())}`:''; const response=await fetch(`${derivApi('/binary/history')}${ownerPrefix}/${encodeURIComponent(accountId(selectedAccount))}?limit=50&offset=0`,{cache:'no-store'}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.detail||`history ${response.status}`); renderHistory(data);}catch(error){console.warn('BINARY_HISTORY_WARNING',error); setText('binaryHistorySummary','Binary history is temporarily unavailable.');}}
  async function refreshExecution(){if(!selectedAccount) return; try{const ownerPrefix=isLegacyAdmin()?`/${encodeURIComponent(getCurrentFlowSignalUserId())}`:''; const response=await fetch(`${derivApi('/binary/execution-status')}${ownerPrefix}/${encodeURIComponent(accountId(selectedAccount))}`,{cache:'no-store'}); if(response.ok) renderExecution(await response.json()); await refreshHistory();}catch(error){console.warn('BINARY_EXECUTION_STATUS_WARNING',error);}}
  async function executeNativeSignal(data){if(executionBusy||!genuineV5Signal(data)) return; const connectionId=localStorage.getItem(CONNECTION_KEY); if(!connectionId) return; const signalId=String(data.signal_id); if(signalId===lastLocalSignalId) return; executionBusy=true; try{setText('binaryStageEligibility','CHECKING'); const response=await fetch(derivApi('/binary/v5/execute'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(adminBody({connection_id:connectionId,signal_id:signalId}))}); const result=await response.json().catch(()=>({})); if(!response.ok) throw new Error(result?.detail||'BINARY_EXECUTION_BLOCKED'); lastLocalSignalId=signalId; await refreshExecution();}catch(error){console.error('BINARY_NATIVE_5M_EXECUTION_ERROR',error); setStatus(error.message==='REAL_BINARY_EXECUTION_DISABLED'?'REAL BINARY EXECUTION DISABLED':safeDerivMessage(error.message,'Binary execution was blocked safely.'),true); setText('binaryStageExecution','BLOCKED');}finally{executionBusy=false;}}
  async function pollBinary(){if(!binaryVisible()||!document.getElementById(BINARY_MODE_ID)) return; try{const response=await fetch(derivApi('/binary/v5/signal'),{cache:'no-store'}); if(!response.ok) throw new Error(`binary signal ${response.status}`); const data=await response.json(), direction=renderSignal(data), available=Boolean(data?.ok); setText('binarySystemResearch',available?'LIVE':'UNKNOWN'); setText('binarySystemRelay',available||data?.reason==='NO_RELAYED_V5_SIGNAL'?'LIVE':'UNKNOWN'); if(direction!=='WAIT') await executeNativeSignal(data); await refreshExecution();}catch(error){console.warn('BINARY_NATIVE_5M_POLL_WARNING',error); renderSignal({signal:'WAIT'}); setText('binarySystemResearch','UNKNOWN'); setText('binarySystemRelay','UNAVAILABLE'); setStatus('Binary data unavailable',true);}}
  function startPolling(){if(pollTimer||!binaryVisible()) return; pollBinary(); pollTimer=setInterval(pollBinary,POLL_MS);}
  function stopPolling(){if(pollTimer){clearInterval(pollTimer); pollTimer=null;}}
  async function refreshAll(){await refreshStatus(); await pollBinary();}
  function mount(){if(mounted) return true; injectCss(); if(!buildModeShell()) return false; mounted=true; if(binaryVisible()) refreshAll(); console.info('BINARY_MODE_SHELL_MOUNTED'); return true;}
  function start(){if(mount()) return; let tries=0; const timer=setInterval(()=>{tries+=1; if(mount()||tries>=40) clearInterval(timer);},250);}
  document.addEventListener('flowsignal:authenticated',()=>setTimeout(start,0)); if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',start,{once:true}); else start(); window.addEventListener('focus',()=>{if(mounted&&binaryVisible()) refreshAll();});
  window.FlowSignalBinary={mount,setMode,currentMode,refreshStatus,pollBinary,refreshExecution,refreshHistory,getCurrentFlowSignalUserId,genuineV5Signal,renderSignal,renderExecution,renderHistory};
})();
